
- hosts: localhost
  gather_facts: False
  vars_files: 
  - secret.yml
  tasks:
  - ec2:
      aws_access_key: "{{ my_access_key }}"
      aws_secret_key: "{{ my_secret_key }}"
      key_name: "Ansible-t2"
      instance_type: "t2.micro"
      image: "ami-0ebc1ac48dfd14136"
      wait: yes
      count: 1
      instance_tags:
              Name: AWS
      vpc_subnet_id: "subnet-00f1e9cec1f388138"
      assign_public_ip: yes
      region: "ap-south-1"
      state: present
      group_id: "sg-0a2b1fc920523d922"
